# This is a basic workflow to help you get started with Actions

name: Generate pandoc pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --html
            ariths_gen
    - name: Upload results
      uses: actions/upload-artifact@v1.0.0
      with:
        name: documentation
        path: html
    - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: html   # The folder the action should deploy.